### ISSUE TITLE
Why images are taking lot of time to load on the Screen from firebase storage?

### ISSUE THREAD

**Issue by chilupa** [sagarchoudhary96/Friendly-Chat-Android#2]
Why images are rendered slow from firebase storage?

I'm able to get the images but they aren't loaded properly. 

This is the [scenario](https://github.com/udacity/and-nd-firebase/issues/18).  

How to fix this @sagarchoudhary96

**Comment by sagarchoudhary96** [comment]
sorry for replying late

**Comment by sagarchoudhary96** [comment]
@pavanchilukuri if you are still facing problem please share the repo link so that i can see to it :)

**Comment by sagarchoudhary96** [comment]
@pavanchilukuri saw you solved it out. if in future you are stuck with some problem, just ping me here with the screen shot or code snippet .. i'll keep watching to this repo from now till you finish up your project and will try to reply to your query ASAP 👍
